import * as pc from './assets/playcanvas.mjs';
import {makeInstructor} from './instructor.mjs';
const canvas=document.querySelector('canvas');
const app=new pc.Application(canvas,{graphicsDeviceOptions:{antialias:true,preserveDrawingBuffer:true,alpha:false}});
app.setCanvasResolution(pc.RESOLUTION_FIXED,1920,1080);
app.scene.ambientLight=new pc.Color(.6,.55,.48);
const camera=new pc.Entity('Shot camera');
camera.addComponent('camera',{fov:60,nearClip:.03,farClip:100,clearColor:new pc.Color(.04,.035,.03)});
app.root.addChild(camera);
const scan=new pc.Entity('FUSEgym • static original capture');
scan.setEulerAngles(0,0,180);app.root.addChild(scan);
const params=new URLSearchParams(location.search);
const asset=new pc.Asset('Gym','gsplat',{url:params.get('asset')||'assets/scene.ply'});
app.assets.add(asset);
asset.on('progress',(received,total)=>{if(total>0)document.querySelector('#label').textContent=`Gym ${Math.round(received/total*100)}%`;});
await new Promise((resolve,reject)=>{asset.once('load',resolve);asset.once('error',reject);app.assets.load(asset)});
scan.addComponent('gsplat',{asset});
window.setView=(p,t,fov=60)=>{camera.setPosition(...p);camera.lookAt(new pc.Vec3(...t));camera.camera.fov=fov;app.renderNextFrame=true;};
window.setView([0,0,3],[0,0,-3]);
const instructor=makeInstructor(pc,app);instructor.root.setPosition(0,-1.20,-.8);
// Analytic soft contact shadows, over the captured floor. No collision inference.
const shadowLayer=new pc.Layer({name:'Contact shadows'});app.scene.layers.pushTransparent(shadowLayer);camera.camera.layers=[...camera.camera.layers,shadowLayer.id];
const texCanvas=document.createElement('canvas');texCanvas.width=128;texCanvas.height=128;const ctx=texCanvas.getContext('2d');const grad=ctx.createRadialGradient(64,64,3,64,64,62);grad.addColorStop(0,'rgba(0,0,0,.75)');grad.addColorStop(.3,'rgba(0,0,0,.55)');grad.addColorStop(.7,'rgba(0,0,0,.16)');grad.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,128,128);
const tex=new pc.Texture(app.graphicsDevice,{mipmaps:true});tex.setSource(texCanvas);
function shadow(name,x,z,w,d,opacity){const m=new pc.StandardMaterial();m.useLighting=false;m.diffuse=new pc.Color(0,0,0);m.emissive=new pc.Color(0,0,0);m.opacityMap=tex;m.opacityMapChannel='a';m.opacity=opacity;m.blendType=pc.BLEND_NORMAL;m.depthWrite=false;m.cull=pc.CULLFACE_NONE;m.update();const e=new pc.Entity(name);e.addComponent('render',{type:'plane',material:m,layers:[shadowLayer.id],castShadows:false});e.setPosition(x,-1.196,z);e.setLocalScale(w,1,d);app.root.addChild(e);return e;}
shadow('Left foot contact',-.205,-.74,.31,.46,.9);shadow('Right foot contact',.205,-.74,.31,.46,.9);const bodyShadow=shadow('Soft body shadow',.04,-.78,1.12,.85,.55);
const key=new pc.Entity('Warm overhead key');key.addComponent('light',{type:'directional',color:new pc.Color(1,.87,.72),intensity:1.7,castShadows:false});key.setEulerAngles(48,-28,0);app.root.addChild(key);
const fill=new pc.Entity('Front soft fill');fill.addComponent('light',{type:'directional',color:new pc.Color(.78,.87,1),intensity:.7});fill.setEulerAngles(15,165,0);app.root.addChild(fill);
const rim=new pc.Entity('Overhead rim');rim.addComponent('light',{type:'directional',color:new pc.Color(1,.93,.81),intensity:1.1});rim.setEulerAngles(55,160,0);app.root.addChild(rim);
window.setTime=t=>{const pose=instructor.pose(t);bodyShadow.setLocalScale(1.12-.18*pose.q,1,.85-.08*pose.q);const u=Math.max(0,Math.min(1,t/15)),ease=u*u*(3-2*u);window.setView([.35,.13,3.7-.65*ease],[-.60-.19*ease,-.35,-.8],47);document.querySelector('#time').value=t;document.querySelector('#label').textContent=t.toFixed(2)+' / 15 s';return pose;};
window.instructor=instructor;
window.setTime(0);
const music=document.querySelector('#music');let playing=false;
document.querySelector('#play').onclick=async()=>{playing=!playing;if(playing){music.currentTime=Number(document.querySelector('#time').value)>=15?0:Number(document.querySelector('#time').value);await music.play();}else music.pause();document.querySelector('#play').textContent=playing?'Pause':'Play';};
document.querySelector('#time').oninput=e=>{playing=false;music.pause();music.currentTime=Number(e.target.value);document.querySelector('#play').textContent='Play';window.setTime(Number(e.target.value));};
app.on('update',()=>{if(playing){window.setTime(Math.min(15,music.currentTime));if(music.ended){playing=false;document.querySelector('#play').textContent='Play';}}});
app.start();
window.app=app;window.camera=camera;window.scan=scan;window.pc=pc;
window.ready=true;document.querySelector('#label').textContent='Ready';
