import type { RefObject } from 'react';
import type { SceneLandmark, ModelLoadStatus, SceneManifest, ViewMode, CameraPose, PathPreview, ViewportRegion, ViewportHandle, ShotSnapshot, ActorPose, ActorPath, ActorTool, ActorTransformEvent, ScenePlacement, SceneTransformEvent, ObjectContextRequest, SceneProp, PropTransformEvent, ActorRigInfo } from '@/contracts';

export type LiveViewportProps = {
  cleanFrame?: boolean;
  onRendered?: (canvas: HTMLCanvasElement) => void;
  landmarkMode?: boolean;
  landmarks?: SceneLandmark[];
  activeLandmarkId?: string | null;
  hideLandmarks?: boolean;
  preview?: { region: ViewportRegion; cameraId: string; pose: CameraPose | null } | null;
  onLandmarkSelect?: (id: string) => void;
  onLandmark?: (landmark: SceneLandmark) => void;
  onLandmarkHint?: (hint: string) => void;
  onModelStatus?: (models: ModelLoadStatus[]) => void;
  actorTool?: ActorTool;
  onActorTransform?: (event: ActorTransformEvent) => void;
  placements?: ScenePlacement[];
  onSceneTransform?: (event: SceneTransformEvent) => void;
  props?: SceneProp[];
  onPropTransform?: (event: PropTransformEvent) => void;
  onContextRequest?: (request: ObjectContextRequest) => void;
  actors?: ActorPose[];
  /** Reports each actor's body once it is built or its model finishes loading. */
  onActorRig?: (id: string, info: ActorRigInfo) => void;
  actorPaths?: ActorPath[];
  pose: CameraPose | null;
  path: PathPreview | null;
  region: ViewportRegion;
  handle: RefObject<ViewportHandle | null>;
  showPath: boolean;
  manifest: SceneManifest;
  mode: ViewMode;
  frame: number;
  cameraId: string;
  selectedId: string | null;
  onSelect: (id: string | null) => void;
  showCameras: boolean;
  onReady: () => void;
};
export type { ShotSnapshot };
